version: "3.9"

services:
  psql-dev:
    image: postgres:15.3-alpine
    ports:
      - "5439:5432"
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_PASSWORD: "qwerty*1234"
      POSTGRES_USER: "postgres"
    healthcheck:
      test: "pg_isready -U postgres -d postgres"
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1GB
    networks:
      - custom
  server-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - psql-dev
    networks:
      - custom
    command: uv run app.py



networks:
  custom:
    driver: bridge