[project]
name = "backend"
version = "0.1.0"
description = "Server for vm manager"
requires-python = ">=3.13"
dependencies = [
    "asyncpg>=0.30.0",
    "bcrypt>=4.2.1",
    "dishka>=1.4.2",
    "environs>=14.1.0",
]
